import { c as create_ssr_component, d as escape, e as each, b as add_attribute, v as validate_component } from "../../../chunks/ssr.js";
import { p as personalInfo } from "../../../chunks/personal.js";
import { p as professionalProjects } from "../../../chunks/projects.js";
const NpmModal = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { show = false } = $$props;
  let { project = null } = $$props;
  let { onClose = () => {
  } } = $$props;
  if ($$props.show === void 0 && $$bindings.show && show !== void 0) $$bindings.show(show);
  if ($$props.project === void 0 && $$bindings.project && project !== void 0) $$bindings.project(project);
  if ($$props.onClose === void 0 && $$bindings.onClose && onClose !== void 0) $$bindings.onClose(onClose);
  return `${show && project ? `<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4" role="button" tabindex="0" aria-label="Close modal"><div class="bg-white dark:bg-dark-900 rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto" role="dialog" aria-modal="true"><div class="p-6"><div class="flex items-center justify-between mb-6"><h2 class="text-2xl font-bold text-dark-900 dark:text-white">${escape(project.title)} - NPM Packages</h2> <button class="text-dark-400 hover:text-dark-600 dark:text-dark-500 dark:hover:text-dark-300 transition-colors duration-200" data-svelte-h="svelte-qkcv9t"><svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg></button></div> <div class="space-y-4">${each(project.npmPackages, (npmPackage) => {
    return `<a${add_attribute("href", npmPackage.url, 0)} target="_blank" rel="noopener noreferrer" class="block border border-dark-200 dark:border-dark-700 rounded-lg p-4 hover:bg-dark-50 dark:hover:bg-dark-800 hover:border-red-300 dark:hover:border-red-600 transition-all duration-200 cursor-pointer group"><div class="flex items-center justify-between mb-2"><h3 class="text-lg font-semibold text-dark-900 dark:text-white group-hover:text-red-600 dark:group-hover:text-red-400 transition-colors duration-200">${escape(npmPackage.name)}</h3> <span class="px-2 py-1 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 text-xs rounded-full font-medium" data-svelte-h="svelte-1mtkdl1">NPM
                </span></div> <p class="text-dark-600 dark:text-dark-300 text-sm group-hover:text-dark-700 dark:group-hover:text-dark-200 transition-colors duration-200">${escape(npmPackage.description)}</p> <div class="mt-3 flex items-center text-red-600 dark:text-red-400 text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity duration-200" data-svelte-h="svelte-1ehvvkw"><span>View on NPM</span> <svg class="w-4 h-4 ml-1 transform group-hover:translate-x-1 transition-transform duration-200" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg></div> </a>`;
  })}</div> <div class="mt-6 pt-4 border-t border-dark-200 dark:border-dark-700" data-svelte-h="svelte-1dd9x9a"><p class="text-sm text-dark-500 dark:text-dark-400 text-center">Choose the package that matches your framework. All packages are built with TypeScript and follow the same design system.</p></div></div></div></div>` : ``}`;
});
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let filteredProjects = professionalProjects;
  let showNpmModal = false;
  let selectedProject = null;
  function closeNpmModal() {
    showNpmModal = false;
    selectedProject = null;
  }
  return `${$$result.head += `<!-- HEAD_svelte-ftfjgr_START -->${$$result.title = `<title>Projects - ${escape(personalInfo.name)}</title>`, ""}<meta name="description" content="${"Professional and personal projects by " + escape(personalInfo.name, true)}"><!-- HEAD_svelte-ftfjgr_END -->`, ""} <div class="min-h-screen bg-white dark:bg-dark-900"> <section class="pt-20 pb-12 bg-gradient-to-br from-primary-50 to-accent-50 dark:from-primary-900/20 dark:to-accent-900/20" data-svelte-h="svelte-11vbx4a"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="text-center"><h1 class="text-4xl md:text-5xl font-bold mb-6 gradient-text">My Projects</h1> <p class="text-xl text-dark-600 dark:text-dark-300 max-w-3xl mx-auto">A showcase of my professional work and personal projects, demonstrating expertise across various technologies and domains.</p></div></div></section>  <section class="py-8 bg-white dark:bg-dark-900 border-b border-dark-200 dark:border-dark-700"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="flex flex-wrap justify-center gap-4"><button class="${[
    "px-6 py-3 rounded-lg font-medium transition-colors duration-200 focus-ring",
    "bg-primary-600 text-white    "
  ].join(" ").trim()}" data-svelte-h="svelte-62pnb2">Professional Projects</button> <button class="${[
    "px-6 py-3 rounded-lg font-medium transition-colors duration-200 focus-ring",
    "  bg-dark-100 dark:bg-dark-800 text-dark-700 dark:text-dark-300"
  ].join(" ").trim()}" data-svelte-h="svelte-12aldrw">Personal Projects</button> <button class="${[
    "px-6 py-3 rounded-lg font-medium transition-colors duration-200 focus-ring",
    "  bg-dark-100 dark:bg-dark-800 text-dark-700 dark:text-dark-300"
  ].join(" ").trim()}" data-svelte-h="svelte-10ib2h8">GitHub Repositories</button></div></div></section>  <section class="py-20"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">${`<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">${each(filteredProjects, (project, index) => {
    return `<div class="animate-scale-in" style="${"animation-delay: " + escape(index * 0.1, true) + "s;"}"><div class="bg-white dark:bg-dark-900 rounded-2xl shadow-lg hover:shadow-xl transition-shadow duration-300 overflow-hidden border border-dark-200 dark:border-dark-700 h-full flex flex-col"> <div class="h-48 bg-gradient-to-br from-primary-100 to-accent-100 dark:from-primary-900/20 dark:to-accent-900/20 flex items-center justify-center" data-svelte-h="svelte-27obo5"><div class="text-4xl">🚀</div></div>  <div class="p-6 flex flex-col flex-grow"><div class="flex items-center justify-between mb-3"><h3 class="text-xl font-bold text-dark-900 dark:text-white line-clamp-2">${escape(project.title)}</h3> ${project.type === "professional" ? `<span class="px-2 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-xs rounded-full" data-svelte-h="svelte-vmp4l6">Professional
                      </span>` : `<span class="px-2 py-1 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 text-xs rounded-full" data-svelte-h="svelte-pjjgc7">Personal
                      </span>`}</div> <p class="text-dark-600 dark:text-dark-300 mb-4 line-clamp-3 min-h-[4.5rem]">${escape(project.description)}</p> ${project.role || project.company ? `<div class="mb-4"><p class="text-sm text-primary-600 dark:text-primary-400">${escape(project.role)} ${project.company ? `• ${escape(project.company)}` : ``}</p> </div>` : ``} ${project.impact ? `<div class="mb-4 p-3 bg-green-50 dark:bg-green-900/20 rounded-lg"><p class="text-sm text-green-700 dark:text-green-300 font-medium" data-svelte-h="svelte-oq5766">Impact:</p> <p class="text-sm text-green-600 dark:text-green-400">${escape(project.impact)}</p> </div>` : ``}  <div class="mb-4"><div class="flex flex-wrap gap-2">${each(project.technologies.slice(0, 4), (tech) => {
      return `<span class="px-2 py-1 bg-dark-100 dark:bg-dark-800 text-dark-700 dark:text-dark-300 text-xs rounded-md">${escape(tech)} </span>`;
    })} ${project.technologies.length > 4 ? `<span class="px-2 py-1 bg-dark-100 dark:bg-dark-800 text-dark-700 dark:text-dark-300 text-xs rounded-md">+${escape(project.technologies.length - 4)} more
                        </span>` : ``} </div></div>  ${project.type === "personal" && (project.stars || project.forks) ? `<div class="flex items-center gap-4 mb-4 text-sm text-dark-500 dark:text-dark-400">${project.stars ? `<span class="flex items-center"><svg class="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path></svg> ${escape(project.stars)} </span>` : ``} ${project.forks ? `<span class="flex items-center"><svg class="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"></path></svg> ${escape(project.forks)} </span>` : ``} </div>` : ``}  <div class="flex gap-3 mt-auto">${project.githubUrl ? `<a${add_attribute("href", project.githubUrl, 0)} target="_blank" rel="noopener noreferrer" class="flex-1 px-4 py-2 bg-dark-100 dark:bg-dark-800 text-dark-700 dark:text-dark-300 text-center rounded-lg hover:bg-dark-200 dark:hover:bg-dark-700 transition-colors duration-200 text-sm font-medium">GitHub
                      </a>` : ``}  ${project.type === "personal" ? `${project.underDevelopment ? `<a href="${"/development-in-progress?title=" + escape(encodeURIComponent(project.title), true) + "&amp;id=" + escape(project.id, true)}" class="flex-1 px-4 py-2 bg-yellow-500 text-white text-center rounded-lg hover:bg-yellow-600 transition-colors duration-200 text-sm font-medium">🚧 In Development
                        </a>` : `${project.liveUrl ? `<a${add_attribute("href", project.liveUrl, 0)} target="_blank" rel="noopener noreferrer" class="flex-1 px-4 py-2 bg-primary-600 text-white text-center rounded-lg hover:bg-primary-700 transition-colors duration-200 text-sm font-medium">🚀 Live Demo
                        </a>` : ``}`}` : ``}  ${project.type === "professional" && project.liveUrl ? `${project.underDevelopment ? `<a href="${"/development-in-progress?title=" + escape(encodeURIComponent(project.title), true) + "&amp;id=" + escape(project.id, true)}" class="flex-1 px-4 py-2 bg-primary-600 text-white text-center rounded-lg hover:bg-primary-700 transition-colors duration-200 text-sm font-medium">Live Demo
                        </a>` : `<a${add_attribute("href", project.liveUrl, 0)} target="_blank" rel="noopener noreferrer" class="flex-1 px-4 py-2 bg-primary-600 text-white text-center rounded-lg hover:bg-primary-700 transition-colors duration-200 text-sm font-medium">Live Demo
                        </a>`}` : ``} ${project.npmPackages && project.isPublished ? `<button class="flex-1 px-4 py-2 bg-red-600 text-white text-center rounded-lg hover:bg-red-700 transition-colors duration-200 text-sm font-medium" data-svelte-h="svelte-6s26ou">NPM
                      </button>` : `${project.npmUrl && project.isPublished ? `<a${add_attribute("href", project.npmUrl, 0)} target="_blank" rel="noopener noreferrer" class="flex-1 px-4 py-2 bg-red-600 text-white text-center rounded-lg hover:bg-red-700 transition-colors duration-200 text-sm font-medium">NPM
                      </a>` : ``}`}</div> </div></div> </div>`;
  })}</div>`}</div></section>  <section class="py-20 bg-dark-50 dark:bg-dark-800" data-svelte-h="svelte-1vkt3h3"><div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 class="text-3xl font-bold mb-4">Interested in Working Together?</h2> <p class="text-xl text-dark-600 dark:text-dark-300 mb-8">I&#39;m always open to discussing new projects and opportunities. Let&#39;s create something amazing together.</p> <div class="flex flex-col sm:flex-row gap-4 justify-center"><a href="/contact" class="px-8 py-4 bg-primary-600 hover:bg-primary-700 text-white font-semibold rounded-lg transition-colors duration-200 focus-ring">Get In Touch</a> <a href="https://github.com/dev-1603" target="_blank" rel="noopener noreferrer" class="px-8 py-4 border-2 border-primary-600 text-primary-600 hover:bg-primary-600 hover:text-white font-semibold rounded-lg transition-colors duration-200 focus-ring">View All on GitHub</a></div></div></section>  ${validate_component(NpmModal, "NpmModal").$$render(
    $$result,
    {
      show: showNpmModal,
      project: selectedProject,
      onClose: closeNpmModal
    },
    {},
    {}
  )}</div>`;
});
export {
  Page as default
};
