import { c as create_ssr_component, d as escape, e as each } from "../../../chunks/ssr.js";
import { w as workExperience } from "../../../chunks/work-experience.js";
import { p as personalInfo } from "../../../chunks/personal.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let currentJob = workExperience.find((job) => job.current);
  return `${$$result.head += `<!-- HEAD_svelte-y2at5m_START -->${$$result.title = `<title>Work Experience - ${escape(personalInfo.name)}</title>`, ""}<meta name="description" content="${"Professional work experience and career timeline of " + escape(personalInfo.name, true)}"><!-- HEAD_svelte-y2at5m_END -->`, ""} <div class="min-h-screen bg-white dark:bg-dark-900"> <section class="pt-20 pb-12 bg-gradient-to-br from-primary-50 to-accent-50 dark:from-primary-900/20 dark:to-accent-900/20"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="text-center"><h1 class="text-4xl md:text-5xl font-bold mb-6 gradient-text" data-svelte-h="svelte-ixq7s5">Work Experience</h1> <p class="text-xl text-dark-600 dark:text-dark-300 max-w-3xl mx-auto">${escape(personalInfo.yearsOfExperience)}+ years of experience building scalable applications across fintech, AI, and SaaS domains.</p></div></div></section>  ${currentJob ? `<section class="py-12 bg-primary-50 dark:bg-primary-900/20"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="bg-white dark:bg-dark-900 rounded-2xl shadow-lg p-8 border border-primary-200 dark:border-primary-800"><div class="flex items-center justify-between mb-6"><div data-svelte-h="svelte-15jm0kt"><span class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-primary-100 dark:bg-primary-900/30 text-primary-800 dark:text-primary-200">Current Role</span></div> <div class="text-sm text-dark-500 dark:text-dark-400">${escape(currentJob.duration)}</div></div> <h2 class="text-2xl font-bold mb-2">${escape(currentJob.title)}</h2> <p class="text-lg text-primary-600 dark:text-primary-400 mb-4">${escape(currentJob.company)} • ${escape(currentJob.location)}</p> <p class="text-dark-600 dark:text-dark-300 mb-6">${escape(currentJob.description)}</p> <div class="flex flex-col gap-6"><div><h3 class="text-lg font-semibold mb-3" data-svelte-h="svelte-6a3yeh">Key Achievements</h3> <ul class="space-y-2">${each(currentJob.achievements, (achievement) => {
    return `<li class="flex items-start"><div class="w-2 h-2 bg-primary-500 rounded-full mt-2 mr-3 flex-shrink-0"></div> <span class="text-dark-700 dark:text-dark-300">${escape(achievement)}</span> </li>`;
  })}</ul></div> <div><h3 class="text-lg font-semibold mb-3" data-svelte-h="svelte-1k4umzc">Technologies</h3> <div class="flex flex-wrap gap-2">${each(currentJob.technologies, (tech) => {
    return `<span class="px-3 py-1 bg-dark-100 dark:bg-dark-800 text-dark-700 dark:text-dark-300 text-sm rounded-full">${escape(tech)} </span>`;
  })}</div></div></div></div></div></section>` : ``}  <section class="py-20"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="relative"> <div class="absolute left-8 top-0 bottom-0 w-1 bg-gradient-to-b from-primary-500 via-primary-400 to-primary-300"></div>  <div class="space-y-12">${each(workExperience, (job, index) => {
    return `<div class="relative animate-slide-up group" style="${"animation-delay: " + escape(index * 0.15, true) + "s;"}"> <div class="absolute left-8 w-6 h-6 bg-primary-500 rounded-full border-4 border-white dark:border-dark-900 shadow-lg z-10 transform -translate-x-1/2 group-hover:scale-125 transition-transform duration-300 flex items-center justify-center">${job.current ? `<div class="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>` : ``}</div>  <div class="ml-20"><div class="bg-white dark:bg-dark-900 rounded-2xl shadow-xl p-8 border border-dark-200 dark:border-dark-700 hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-2 hover:scale-[1.02] group-hover:border-primary-300 dark:group-hover:border-primary-600"><div class="flex flex-col md:flex-row md:items-center md:justify-between mb-6"><div><h3 class="text-2xl font-bold text-dark-900 dark:text-white mb-2">${escape(job.title)}</h3> <p class="text-lg text-primary-600 dark:text-primary-400 mb-1">${escape(job.company)}</p> <p class="text-dark-600 dark:text-dark-400">${escape(job.location)}</p></div> <div class="mt-4 md:mt-0"><span class="inline-flex items-center px-4 py-2 rounded-full text-sm font-medium bg-dark-100 dark:bg-dark-800 text-dark-700 dark:text-dark-300">${escape(job.duration)}</span> ${job.current ? `<span class="ml-2 inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-200 animate-pulse" data-svelte-h="svelte-hg2f8s">Current
                        </span>` : ``} </div></div> <p class="text-dark-600 dark:text-dark-300 mb-6 text-lg">${escape(job.description)}</p> <div class="grid md:grid-cols-2 gap-8"> <div class="space-y-6"><div><h4 class="font-semibold text-dark-900 dark:text-white mb-3 text-lg" data-svelte-h="svelte-10mmta1">Key Highlights</h4> <div class="flex flex-wrap gap-2">${each(job.highlights, (highlight) => {
      return `<span class="px-3 py-2 bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 text-sm rounded-full font-medium hover:bg-primary-200 dark:hover:bg-primary-900/50 transition-colors duration-200">${escape(highlight)} </span>`;
    })} </div></div> <div><h4 class="font-semibold text-dark-900 dark:text-white mb-3 text-lg" data-svelte-h="svelte-1gqegxw">Roles &amp; Responsibilities</h4> <ul class="space-y-3">${each(job.roles.slice(0, 5), (role) => {
      return `<li class="flex items-start group/item"><div class="w-2 h-2 bg-primary-500 rounded-full mt-2 mr-3 flex-shrink-0 group-hover/item:scale-150 transition-transform duration-200"></div> <span class="text-sm text-dark-700 dark:text-dark-300 group-hover/item:text-primary-600 dark:group-hover/item:text-primary-400 transition-colors duration-200">${escape(role)}</span> </li>`;
    })} ${job.roles.length > 5 ? `<li class="text-sm text-primary-600 dark:text-primary-400 font-medium hover:text-primary-700 dark:hover:text-primary-300 transition-colors duration-200 cursor-pointer">+${escape(job.roles.length - 5)} more responsibilities
                            </li>` : ``}</ul> </div></div>  <div class="space-y-6"><div><h4 class="font-semibold text-dark-900 dark:text-white mb-3 text-lg" data-svelte-h="svelte-14apq7a">Key Achievements</h4> <ul class="space-y-3">${each(job.achievements.slice(0, 4), (achievement) => {
      return `<li class="flex items-start group/item"><div class="w-2 h-2 bg-green-500 rounded-full mt-2 mr-3 flex-shrink-0 group-hover/item:scale-150 transition-transform duration-200"></div> <span class="text-sm text-dark-700 dark:text-dark-300 group-hover/item:text-green-600 dark:group-hover/item:text-green-400 transition-colors duration-200">${escape(achievement)}</span> </li>`;
    })} ${job.achievements.length > 4 ? `<li class="text-sm text-green-600 dark:text-green-400 font-medium hover:text-green-700 dark:hover:text-green-300 transition-colors duration-200 cursor-pointer">+${escape(job.achievements.length - 4)} more achievements
                            </li>` : ``} </ul></div> <div><h4 class="font-semibold text-dark-900 dark:text-white mb-3 text-lg" data-svelte-h="svelte-1cin947">Technologies</h4> <div class="flex flex-wrap gap-2">${each(job.technologies.slice(0, 8), (tech) => {
      return `<span class="px-3 py-2 bg-primary-50 dark:bg-primary-900/20 text-primary-700 dark:text-primary-300 text-sm rounded-lg hover:bg-primary-100 dark:hover:bg-primary-900/40 transition-colors duration-200 cursor-pointer">${escape(tech)} </span>`;
    })} ${job.technologies.length > 8 ? `<span class="px-3 py-2 bg-dark-100 dark:bg-dark-800 text-dark-700 dark:text-dark-300 text-sm rounded-lg hover:bg-dark-200 dark:hover:bg-dark-700 transition-colors duration-200 cursor-pointer">+${escape(job.technologies.length - 8)} more
                            </span>` : ``} </div></div> </div></div> ${job.majorProjects ? `<div class="mt-8 pt-6 border-t border-dark-200 dark:border-dark-700"><h4 class="font-semibold text-dark-900 dark:text-white mb-4 text-lg" data-svelte-h="svelte-1rcvdyh">Major Projects</h4> <div class="grid md:grid-cols-2 gap-4">${each(job.majorProjects, (project) => {
      return `<div class="p-4 bg-dark-50 dark:bg-dark-800 rounded-lg hover:bg-dark-100 dark:hover:bg-dark-700 transition-colors duration-200 cursor-pointer group"><h5 class="font-medium text-dark-900 dark:text-white text-sm mb-2 group-hover:text-primary-600 dark:group-hover:text-primary-400 transition-colors duration-200">${escape(project.name)}</h5> <p class="text-xs text-dark-600 dark:text-dark-400 group-hover:text-dark-700 dark:group-hover:text-dark-300 transition-colors duration-200">${escape(project.description)}</p> </div>`;
    })}</div> </div>` : ``} </div></div> </div>`;
  })}</div></div></div></section>  <section class="py-20 bg-dark-50 dark:bg-dark-800" data-svelte-h="svelte-57cv45"><div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 class="text-3xl font-bold mb-4">Ready to Work Together?</h2> <p class="text-xl text-dark-600 dark:text-dark-300 mb-8">I&#39;m always interested in new opportunities and exciting projects. Let&#39;s discuss how I can help bring your ideas to life.</p> <div class="flex flex-col sm:flex-row gap-4 justify-center"><a href="/contact" class="px-8 py-4 bg-primary-600 hover:bg-primary-700 text-white font-semibold rounded-lg transition-colors duration-200 focus-ring">Get In Touch</a> <a href="/projects" class="px-8 py-4 border-2 border-primary-600 text-primary-600 hover:bg-primary-600 hover:text-white font-semibold rounded-lg transition-colors duration-200 focus-ring">View My Projects</a></div></div></section></div>`;
});
export {
  Page as default
};
