name: Build and Deploy Svelte App

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAGES: true
      DATABASE_URL: ./build.db  # <-- Now available to all steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
          build_path: ./build
          public_base_path: /portfolio
          package_manager: yarn