name: Build and Deploy to dev-1603.github.io

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ./build.db
      GITHUB_PAGES: true
      NODE_ENV: "production"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: dev-1603/dev-1603.github.io
          publish_branch: main
          publish_dir: ./build
          force_orphan: true
          commit_message: "Deploy from portfolio-website - ${{ github.sha }}"